[phases.setup]
nixPkgs = ["jdk21", "maven"]

[phases.build]
cmds = ["./mvnw clean package -DskipTests"]

[start]
cmd = "java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar target/chatapp.jar"
