services:
  - type: web
    name: chatapp-backend
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar target/chatapp.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_haiKWqIR9Ox8@ep-winter-frog-a1eoplgy-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        value: 26866a08af33947a70ee68be7b5b63226c14d7ce492a870f558ce8f082e27aba
      - key: FRONTEND_URL
        value: https://chatappfsd.vercel.app
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: UPLOAD_DIR
        value: /tmp/uploads
      - key: JAVA_TOOL_OPTIONS
        value: -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
